# zerobill/docker-compose.yml
version: '3.8'

services:
  # --- Database Service ---
  mongodb:
    image: mongo:latest
    container_name: zerobill-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always 
    networks:
      - zerobill-net

  # --- Cache/Queue Service ---
  redis:
    image: redis:7-alpine
    container_name: zerobill-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always 
    networks:
      - zerobill-net

  # --- API Service (Web Server) ---
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zerobill-api
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    # Use the production start script
    command: npm start
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - zerobill-net
  
  # --- Worker Service (Job Processor) ---
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zerobill-worker
    env_file:
      - ./backend/.env
    # Use the production worker script
    command: npm run start:worker
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - zerobill-net

# Define a shared network for services to communicate
networks:
  zerobill-net:
    driver: bridge

# Define persistent volumes
volumes:
  mongo-data:
  redis-data: